# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - script: ls
  - script: dotnet build --configuration $(buildConfiguration) NEte/NEte.sln
    displayName: 'dotnet build'
  - script: dotnet test NEte/NEte.UnitTests/NEte.UnitTests.csproj
    displayName: 'dotnet test'
  - script: dotnet pack NEte/NEte/NEte.csproj --configuration $(buildConfiguration) -p:PackageVersion=1.0.$(BuildID)
    displayName: 'dotnet pack'
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: 'NEte/NEte/bin/Release/NEte.1.0.0.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'MagmaSoftwareNuget'